name: Pipeline testing and dockerize to docker registry

on:
  push:
    branches:
    - master

jobs:
  running-project-test:
    strategy:
      matrix:
        go-version: [1.15.x]
        # Operative systems allowed [ubuntu-latest, macos-latest, windows-latest]
        # [solved] Windows OS ommited because have problem with gcc
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test

  
  running-project-dockerize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build N push Docker Image
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tag_with_ref: true
          tag_with_sha: false
          tags: ${{ github.sha }}